# Generated by Django 4.0.3 on 2022-03-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=128, verbose_name='Короткое наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='DirectoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Версия')),
                ('start_date', models.DateField(verbose_name='Дата начала действия справочника этой версии')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='terminology.directory', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=256, verbose_name='Значение элемента')),
                ('directory_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.directoryversion', verbose_name='Версия справочника')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='terminology.item', verbose_name='Родительский идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
        migrations.AddConstraint(
            model_name='directoryversion',
            constraint=models.UniqueConstraint(fields=('directory', 'version'), name='unique_directory_version'),
        ),
        migrations.AddConstraint(
            model_name='directoryversion',
            constraint=models.UniqueConstraint(fields=('directory', 'start_date'), name='unique_directory_start_date'),
        ),
    ]
